### PR TITLE
Redirect to valid entity results page when no autosuggestion result used - Closes #946

### LINKED ISSUE #946: Autosuggest should redirect properly when not using suggested results - Delegate search #745
### Expected behaviour
When no suggestions present, autosuggest should:
```
get current value typed in input
match against existing patters, {address, transactions}
if match
 use proper url {/explorer/account/address, /explorer/account/address?id=transactionId}
else
 use /explorer/result/inputVal

```

### Actual behaviour
When quick C&P an address in autosuggest field, and hitting immediately afterwards Enter key, autosuggest understands is a non existing record, and redirects to /explorer/result/. 
### Steps to reproduce

- child of #745

### PR DESCRIPTION
**Pull request by faival**
### What was the problem?
- using a valid address, or transaction id, was not redirecting properly to the entity results page. 

### How did I fix it?
- add pattern matching and reuse redirection method in case of match
### How to test it?
- copy a valid {transactionId, addressId}, really quickly paste it on the autosuggest field and immediately press enter without giving time for the search to be triggered. 
- the result should be the same, as when suggestion is shown and a click is performed on it. 
### Review checklist
- The PR solves #946 
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by michaeltomasik** [comment]
How To test it ?

File: src/components/autoSuggest/index.js [hunk 1]
```diff
@@ -81,8 +81,18 @@ class AutoSuggest extends React.Component {
   }
 
   submitAnySearch() {
-    this.inputRef.blur();
-    this.props.history.push(`${routes.searchResult.pathPrefix}${routes.searchResult.path}/${encodeURIComponent(this.state.value)}`);
+    let searchType = null;
+    if (this.state.value.match(regex.address)) {
+      searchType = 'addresses';
+    } else if (this.state.value.match(regex.transactionId)) {
+      searchType = 'transactions';
```
Comment (michaeltomasik) [inline src/components/autoSuggest/index.js]: Please put this strings to constants file
