### PR TITLE
Switch 1 month graph option to 2 weeks - Closes #800

### LINKED ISSUE #800: One month chart is only displaying two weeks on hub dashboard
### Expected behaviour
Chart showing correct period of time
### Actual behaviour
39832618-61aa2934-5363-11e8-9c20-df048e045294

### Steps to reproduce
Go to dashboard, select 1 month on chart

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What was the problem?
The graph didn't have enough data for 1 month
### How did I fix it?
Changed 1 month to 14 days
### How to test it?
Go to dashboard and check 14 days graph option
### Review checklist
- The PR solves #800
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/dashboard/currencyGraph.js [hunk 1]
```diff
@@ -135,10 +135,11 @@ const steps = [
       minUnit: 'day',
     },
   },
+  // Not enough data from endpoint to make 1 month (max 19 days)
   {
-    title: '1m',
+    title: '14d',
```
Comment (faival) [inline src/components/dashboard/currencyGraph.js]: would it be more comprehensible to use `2w` label?
