### PR TITLE
Dont allow to call API when going on Delegate statistics page - Closes #879

### LINKED ISSUE #879: Delegate statistics sends request transactionFilterSet
### Expected behaviour
- Showing the active tab should be handled separately from setting a transactions filter
### Actual behaviour
- It triggers request with wrong filter set.

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What was the problem?
Clicking on `Delegate Statistic` tab was triggering unnecessary API call with the wrong filter value
### How did I fix it?
Changed action for additional tabs
### How to test it?
Open `Network` console and change tab t o`Delegate Statistics` check if it triggers any API call
### Review checklist
- The PR solves #879
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/actions/search.js [hunk 1]
```diff
@@ -57,6 +57,16 @@ export const searchAccount = ({ activePeer, address }) =>
     });
   };
 
+export const setSearchTranactions = searchObj => ({
```
Comment (faival) [inline src/actions/search.js]: IMHO, this action is only used to set the filter, no need to pass address, transactions or count. Also the name of the action is not reflecting the change in the state.

File: src/actions/filters.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import actionTypes from '../constants/actions';
+// eslint-disable-next-line
+export const addFilter = ({ filterName, value }) => ({
```
Comment (faival) [inline src/actions/filters.js]: all actions use the key `data` to store the action data. Let's please use the same pattern here.
