### PR TITLE
No result screen showing before tx loaded - Closes #1882

### LINKED ISSUE #1882: Tx Details: No results screen is shown before tx loaded
### Steps to reproduce

1. Click on some tx in Wallet or use the direct link or use search suggestions to open valid tx

### Actual result

Before showing valid loaded details you can see the No results screen

### Expected result

?

### Screenshot (if appropriate)

image

### PR DESCRIPTION
**Pull request by massao**
### What issue have I solved?

#1882 

### How have I implemented/fixed it?

Added condition to only show the no result screen if request returns no result.

### How has this been tested?

You can throttle the network to delay the loading of the tx.
- Click on some tx in Wallet or use the direct link or use search suggestions to open valid tx.
- No result screen should not flash before the tx loaded.

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/singleTransactionV2/singleTransactionV2.js [hunk 1]
```diff
@@ -146,7 +146,7 @@ class SingleTransactionV2 extends React.Component {
             </footer>
           </main>
         </BoxV2>
-      ) : (
+      ) : this.props.transaction && typeof this.props.transaction === 'string' && (
```
Comment (osvaldovega) [inline src/components/singleTransactionV2/singleTransactionV2.js]: you just need to use` transaction && typeof transaction === 'string' `as you already use destructuring in the top

File: src/components/singleTransactionV2/singleTransactionV2.test.js [hunk 2]
```diff
@@ -164,4 +164,31 @@ describe('Single Transaction V2 Component', () => {
       expect(wrapper.find('.detailsHeader h1')).toHaveText('Vote Transaction');
     });
   });
+
+  describe('No results', () => {
+    const transaction = 'No transction found';
```
Comment (osvaldovega) [inline src/components/singleTransactionV2/singleTransactionV2.test.js]: typo transction
