### PR TITLE
Styling of sign message - Closes #880

### LINKED ISSUE #880: Styling of Sign message
### Expected behaviour

Simple, yet visually fitting process to signal future support for delegates (sign a message). Explanation what's happening technically to understand the context. Signing a message is familiar to cryptography savvy people, but laymen don't understand the terms.

### Actual behaviour

No explanation what the system is doing (technically) with passphrase input. Does it cost something, does it broadcast the key etc etc.
Also slight design differences comparing to the rest of Hub.

screen shot 2018-06-05 at 11 46 50screen shot 2018-06-05 at 11 47 05screen shot 2018-06-05 at 11 47 16

#### 1st screen

Change text into "You can use your passphrase to encrypt a message. This encrypted message can prove that you are the owner of the account, since only your passphrase can produce it. We recommend including date & time or a specific keyword."

#### 2nd screen

Headline "Sign in with the passphrase to encrypt with"

#### 3rd screen

Get rid of the dark box, make container width the same as text on 1st screen
Copy text for the message (looks scary enough already) Open Sans Regular #3C5068
'Copy to clipboard' button needs more space between message and button, I'd say 48 px

### Steps to reproduce

https://jenkins.lisk.io/test/lisk-hub/PR-873/#/sign-message

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What was the problem?
Wrong styles and texts on signedMessage
### How did I fix it?
apply new styles and text
### How to test it?
Go to `/signed-message` and compare tests
### Review checklist
- The PR solves #880
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by hpbaxxtr** [comment]
Let's use the background color #06213B for the signed message box at least, aligning it with lisk.io/documentation

File: src/components/signMessage/signMessage.js [hunk 1]
```diff
@@ -15,7 +15,9 @@ class SignMessage extends React.Component {
   render() {
     const { account, t, history } = this.props;
     const header = t('Sign a message');
-    const message = t('Signing a message with this tool indicates ownership of a privateKey (secret) and provides a level of proof that you are the owner of the key.');
+    const message = t('You can use your passphrase to encrypt a message. ' +
```
Comment (slaweet) [inline src/components/signMessage/signMessage.js]: `sign` not `encrypt`. Signed message is not encrypted

File: src/components/signMessage/signMessage.js [hunk 2]
```diff
@@ -15,7 +15,9 @@ class SignMessage extends React.Component {
...
+      'This encrypted message can prove that you are the owner of the account, ' +
+      'since only your passphrase can produce it. We recommend including date & time or a specific keyword.');
```
Comment (slaweet) [inline src/components/signMessage/signMessage.js]: Translation function parses doesn't like strings split into multiple lines (see it's missing in the generated common.json)

File: src/components/signMessage/confirmMessage.js [hunk 3]
```diff
@@ -65,7 +65,7 @@ class ConfirmMessage extends React.Component {
         <header>
           <div className={styles.tableCell}>
             <TransitionWrapper current={this.state.step} step='verify'>
-              <h2 className={styles.verify}>{this.props.t('Please sign in with your passphrase')}</h2>
+              <h2 className={styles.verify}>{this.props.t('Sign in with the passphrase to encrypt with')}</h2>
```
Comment (slaweet) [inline src/components/signMessage/confirmMessage.js]: `sign`, not `encrypt`

File: src/components/signMessage/confirmMessage.css [hunk 4]
```diff
@@ -6,7 +6,9 @@
 }
 
 .address {
-  padding: 15px 48px;
+  padding: 15px 32px;
+  font-family: 'Open Sans';
```
Comment (slaweet) [inline src/components/signMessage/confirmMessage.css]: we have css variables for fonts, please use one.

File: src/components/signMessage/signMessage.js [hunk 5]
```diff
@@ -15,7 +15,9 @@ class SignMessage extends React.Component {
   render() {
     const { account, t, history } = this.props;
     const header = t('Sign a message');
-    const message = t('Signing a message with this tool indicates ownership of a privateKey (secret) and provides a level of proof that you are the owner of the key.');
+    const message = t('You can use your passphrase to encrypt a message. ' +
+      'This encrypted message can prove that you are the owner of the account, ' +
```
Comment (slaweet) [inline src/components/signMessage/signMessage.js]: `signed` not `encrypted`

File: src/components/signMessage/confirmMessage.css [hunk 6]
```diff
@@ -82,14 +85,14 @@
...
+  padding: 20px 180px;
   background-color: var(--color-form-bg);
 
   & textarea {
-    background: #333;
+    background: #06213b;
     border-radius: 5px;
     overflow: auto;
-    color: var(--color-white);
+    color: #9bf436;
```
Comment (slaweet) [inline src/components/signMessage/confirmMessage.css]: All colors should be defined in `src/components/app/variables.css` in case we want to do a night mode in the future

File: src/components/signMessage/signMessage.js [hunk 7]
```diff
@@ -15,7 +15,9 @@ class SignMessage extends React.Component {
   render() {
     const { account, t, history } = this.props;
     const header = t('Sign a message');
-    const message = t('Signing a message with this tool indicates ownership of a privateKey (secret) and provides a level of proof that you are the owner of the key.');
+    const message = t('You can use your passphrase to sign a message. ') +
+      t('This signed message can prove that you are the owner of the account, ') +
+      t('since only your passphrase can produce it. We recommend including date & time or a specific keyword.');
```
Comment (slaweet) [inline src/components/signMessage/signMessage.js]: It's not good to split one sentence into multiple translation strings, because in another language the sentence structure might be different and also the translators will miss the context of where the sentence starts.
