### PR TITLE
Voting feature should pass e2e tests migration 1.0.0 - Closes #969

### LINKED ISSUE #969: Explorer feature should pass e2e - Voting -  1.0.0 Migration #812
### Expected behaviour
All tests are passing test/e2e/voting.feature:Feature: Voting page
### Actual behaviour
After enabling 1.0.0 usage, some test will fail, and should be fixed.

### PR DESCRIPTION
**Pull request by faival**
### What was the problem?
- voting was using lisk-js
### How did I fix it?
- voting is using lisk-elements
### Review checklist
- The PR solves #969 
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/utils/api/delegate.js [hunk 1]
```diff
@@ -19,15 +19,25 @@ export const vote = (activePeer, secret, publicKey, voteList, unvoteList, second
...
 
 export const getVoters = (activePeer, publicKey) =>
-  requestToActivePeer(activePeer, 'delegates/voters', { publicKey });
+  activePeer.voters.get({ publicKey });
 
-export const registerDelegate = (activePeer, username, secret, secondSecret = null) => {
-  const data = { username, secret };
-  if (secondSecret) {
-    data.secondSecret = secondSecret;
+export const registerDelegate = (activePeer, username, passphrase, secondPassphrase = null) => {
```
Comment (michaeltomasik) [inline src/utils/api/delegate.js]: Is registerDelegate part of the same ticket ?

Comment (slaweet) [reply src/utils/api/delegate.js]: It shouldn't be, there is a separate PR for that https://github.com/LiskHQ/lisk-hub/pull/972 but I see that some commits are in both PRs
