### PR TITLE
Send features, show single Transactions migration to 1.0.0 - Closes #967

### LINKED ISSUE #967: Send feature should pass e2e - 1.0.0 Migration #812
### Expected behaviour
All tests are passing test/e2e/send.feature:Feature: Send dialog
### Actual behaviour
After enabling 1.0.0 usage, some test will fail, and should be fixed.

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What was the problem?
old implementation
### How did I fix it?
Migrated to 1.0.0
### Review checklist
- The PR solves #967
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/utils/api/transactions.js [hunk 1]
```diff
@@ -25,14 +27,15 @@ export const getTransactions = ({
...
 
-export const unconfirmedTransactions = (activePeer, address, limit = 20, offset = 0, orderBy = 'timestamp:desc') =>
-  requestToActivePeer(activePeer, 'transactions/unconfirmed', {
-    senderId: address,
-    recipientId: address,
-    limit,
-    offset,
-    orderBy,
+export const unconfirmedTransactions = (activePeer, address, limit = 20, offset = 0, sort = 'timestamp:desc') =>
+  new Promise(() => {
```
Comment (faival) [inline src/utils/api/transactions.js]: Please don't wrap a promise as the getTransactions is already returning a Promise.

File: src/actions/transactions.js [hunk 2]
```diff
@@ -108,8 +108,9 @@ export const loadTransaction = ({ activePeer, id }) =>
     dispatch({ type: actionTypes.transactionCleared });
     getSingleTransaction({ activePeer, id })
       .then((response) => {
-        const added = (response.transaction.votes && response.transaction.votes.added) || [];
-        const deleted = (response.transaction.votes && response.transaction.votes.deleted) || [];
+        const transaction = response.data[0];
+        const added = (transaction.votes && transaction.votes.added) || [];
```
Comment (faival) [inline src/actions/transactions.js]: I think the api changed, and now the object to be used is transaction.asset.votes, and requires to filter added & removed.
see
https://github.com/LiskHQ/lisk-hub/blob/99ae7afc92a7b796ef4b9f6299ba18a027277966/src/actions/transactions.js#L111
