### PR TITLE
Search fix: suggestions and 3 letters message - Closes #1568

### LINKED ISSUE #1568: "No results found" after finding results
After a successful search, clicking in the search field again results in a "No results found" message.

### Steps to reproduce

1.  Open lisk hub
2. Search for korben3.
3. Correct results appear.
4. Click in the search input field and press enter again, without changing or removing the current value. 
5. Page shows "No results".

### Actual result
No results.

### Expected result
Show found search results.

### Version
1.7.0

### Screenshot (if appropriate)
image

### PR DESCRIPTION
**Pull request by Efefefef**
### What issue have I solved?

#1568

### How have I implemented/fixed it?

Show 3 letters message if < 3 chars in the input field
Don't clear results after submitting search
Rename empty result text to 'Search for Lisk ID, Delegate or Transaction ID'

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/autoSuggest/index.js [hunk 1]
```diff
@@ -343,11 +352,7 @@ class AutoSuggest extends React.Component {
             />
             : null
           }
-
-          { this.state.value !== '' && this.state.resultsLength === 0 ?
-            <p className={styles.noResults}>{t('No results found')}</p>
-            : null
-          }
+          {<p className={styles.noResults}>{t(getNoResultMessage())}</p>}
```
Comment (slaweet) [inline src/components/autoSuggest/index.js]: The translation `t(...)` function should be inside the `getNoResultMessage` on each string. Because of the script that generates the `common.json` file. This way it won't see the strings.

Comment (slaweet) [reply src/components/autoSuggest/index.js]: Also the `{...}` around the `<p>` are not necessary without the ternary operator.

File: src/components/autoSuggest/index.js [hunk 2]
```diff
@@ -260,10 +259,16 @@ class AutoSuggest extends React.Component {
...
-
   render() {
     const { t } = this.props;
 
+    const getNoResultMessage = () => {
+      let noResultMessage;
+      if (this.state.value.length > 0 && this.state.value.length <= 2) noResultMessage = 'Type at least 3 characters';
+      if (this.state.value.length > 2 && this.state.resultsLength === 0) noResultMessage = 'No results found';
+      return noResultMessage;
+    };
```
Comment (slaweet) [inline src/components/autoSuggest/index.js]: I thought `getNoResultMessage` would be a separate method outside of `render`. `render` is quite long anyway.


The code-base mostly uses `if-else` with curlies and separate lines. Please adhere to this style:
https://github.com/LiskHQ/lisk-hub/blob/81e6c9f46d12947a8cc4a5b2c024db5eb34571df/src/components/autoSuggest/index.js#L165-L169
