### PR TITLE
Fix for autoupdate error - Closes #808

### LINKED ISSUE #808: Error in auto updater
This happened when clicking "Update now" after clicking menu -> Help -> "Check for updates..."

screen shot 2018-05-09 at 16 23 20

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What was the problem?
https://github.com/LiskHQ/lisk-hub/issues/808
### How did I fix it?
Added `window.close();` to UpdateApp
### How to test it?
Click "Update now" after clicking menu -> Help -> "Check for updates..."
### Review checklist
- The PR solves #808
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: app/src/modules/updateModal.js [hunk 1]
```diff
@@ -31,7 +31,6 @@ export default (electron, releaseNotes, updateCallBack, versions) => {
     win.show();
   }, 1000);
   ipcMain.on('update', () => {
-    win.close();
```
Comment (slaweet) [inline app/src/modules/updateModal.js]: I think you need to call
`ipcMain.removeAllListeners('update')` 
before 
`ipcMain.on('update', () => {	`
To prevent `updateCallBack();` being called twice in case I close the update window and open it again from the OS menu

https://electronjs.org/docs/api/ipc-renderer#ipcrendererremovealllistenerschannel
