### PR TITLE
Fix sending BTC with decimal points - Closes #2571

### LINKED ISSUE #2571: BTC: Transaction fee is invalid for decimals in Deutsch
### Steps to reproduce

1. Switch to Deutsch
1. Switch to BTC
1. Try to send some decimal amount of money

### Actual result

Impossible to send transaction

### Expected result

Fee validation understands deutsch notation

### Version

1.21, 1.22

### Screenshot (if appropriate)

image

### PR DESCRIPTION
**Pull request by slaweet**
### What issue have I solved?

Closes #2571

But it happened the same in German and English localization

### How have I implemented/fixed it?

Fix disabled condition of submit button in BTC send form

It was wrong because formBtc was storing state.fields.amount.error
and passing it in props.extraFields to formBase.

Solved by merging fields and extraFields so that amount from fields is used.

The other problem was that the dynamic fee was computed based on the previous state of the amount. I fixed this by moving the fee update only after amount state is updated.

### How has this been tested?

Follow steps in #2571

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/screens/wallet/send/form/formBtc.js [hunk 1]
```diff
@@ -114,14 +120,14 @@ export default class FormBtc extends React.Component {
...
-  getCalculatedDynamicFee(dynamicFeePerByte, value) {
+  getCalculatedDynamicFee(dynamicFeePerByte) {
     const { fields: { amount }, unspentTransactionOutputs } = this.state;
     if (amount.error) {
       return 0;
     }
     const feeInSatoshis = btcTransactionsAPI.getTransactionFeeFromUnspentOutputs({
       unspentTransactionOutputs,
-      satoshiValue: toRawLsk(value || amount.value),
+      satoshiValue: toRawLsk(amount.value),
```
Comment (osvaldovega) [inline src/components/screens/wallet/send/form/formBtc.js]: 💅🏻 Vit just a minor thing, I know you didn't change the whole function but maybe you can update it to something like this.

```suggestion
      getDynamicFeeCalculation(dynamicFeePerByte) {
    const { fields: { amount }, unspentTransactionOutputs } = this.state;
    return amount.error
    ? 0;
    : btcTransactionsAPI.getTransactionFeeFromUnspentOutputs({
      unspentTransactionOutputs,
      satoshiValue: toRawLsk(amount.value),
      dynamicFeePerByte,
    });
  }
```

File: src/components/screens/wallet/send/form/formBtc.js [hunk 2]
```diff
@@ -114,14 +120,14 @@ export default class FormBtc extends React.Component {
   }
 
   // TODO move dynamic fee calculation and presentation to a separate component
```
Comment (osvaldovega) [inline src/components/screens/wallet/send/form/formBtc.js]: 💅🏻based on our conversation this comment can be remove as the function will remain in this file
