### PR TITLE
Fix network showing for mainnet - Closes #1251

### LINKED ISSUE #1251: Network indicator is not shown if 'Switch Networks' is off
### Steps to reproduce

1. Turn on 'Switch Networks' in settings
1. Login in test or dev net
1. Turn off 'Switch Networks'
1. Logout

### Actual result
Network indicator disappears
In a logged out state, I have an impression I am searching in mainnet

### Expected result
Network indicator is not dependant on 'Switch Networks'

### PR DESCRIPTION
**Pull request by faival**
### What issue have I solved?

-- #1251 

### How have I implemented/fixed it?

* show it in mainnet if settings enabled
* showing always otherwise

### How has this been tested?

login to the three networks, with or without settings enabled
### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/account/account.js [hunk 1]
```diff
@@ -27,8 +27,11 @@ const Account = ({ peers, t, showNetworkIndicator }) => {
     <FontIcon className={`${styles.network} online`} value={iconMap[iconCode]} /> :
     <FontIcon className='offline' value='error' />;
 
-  return ((showNetworkIndicator && peers.data &&
-      peers.options.code !== networks.mainnet.code) ?
+  const shouldShowNetworkIndicator = ((peers.data &&
+    peers.options.code !== networks.mainnet.code) ||
+    (peers.data && peers.options.code === networks.mainnet.code && showNetworkIndicator));
```
Comment (slaweet) [inline src/components/account/account.js]: The condition can be simplified to:
```
const shouldShowNetworkIndicator = (peers.data && 
  (showNetworkIndicator || peers.options.code !== networks.mainnet.code));
```
