### PR TITLE
Fix strings - Closes #1320

### LINKED ISSUE #1320: Fix strings after copywriter review
The following strings need to be updated:

- [x] Votes of this account -> Votes from this account
- [x] Delegates have great responsibility within the Lisk system, securing the blockchain. -> Delegates have great responsibility within the Lisk system for securing the blockchain.
- [x] Max 20 characters a-z 0-1, no special characters except “!@$&.” -> Max 20 characters, a-z and 0-1, no special characters except for “!@$&.”
- [x] Once you register the name -> Once you register a name
- [x] Go To Your Dashboard -> Go to your Dashboard
- [x] Delegate Registration -> Delegate registration
- [x] Request Specific Amount -> Request specific amount What is request for? No explanation
- [x] Request LSK to -> Requesting LSK to
- [x] Request amount (LSK) -> Amount requested (LSK)
- [x] Ok, I'm Done -> Ok, I'm done
- [x] Are you sure to confirm this selection? -> Are you certain of your choice?
- [x] You’re votes are being processed and will be confirmed. -> Your votes are being processed.
- [x] It may take up to 10 minutes to be secured in the blockchain. -> It may take up to 10 minutes for it to be secured in the blockchain.
- [x] Sidechains will revolutionize the way decentralised apps are developed. -> Sidechains will revolutionize the way decentralized apps are developed.
- [x] After registration, you will need it to use your Lisk ID, like sending and voting. -> After registration, your second passphrase will be required when confirming every transaction and every vote.
- [x] You are responsible for keeping your 2nd passphrase safe -> You are responsible for safekeeping your second passphrase.
- [x] 2nd passphrase -> second passphrase
- [x] You're almost finished -> You're almost done
- [x] Your session was timed out after 10 minutes of no network activitiy. -> Your session was timed out after 10 minutes of no network activity.
- [x] Search through our tutorials, FAQs or connect to our community all over the world. -> Browse through our tutorials, check out the FAQ or connect with our knowledgeable community.
- [x] Search for advice and answers in our extensive  FAQ or get in touch in the Chat. -> Search for answers in our extensive FAQ or get in touch via Chat.
- [x] The Lisk Academy aims to make learning about blockchain technology interactive and enjoyable. -> Learn about blockchain with our comprehensive knowledge base.
- [x] Don’t be a stranger! Connect to our community all over the world. -> Don’t be a stranger! Connect with our worldwide community.

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What issue have I solved?

-- #1320

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/setting/setting.js [hunk 1]
```diff
@@ -69,7 +69,7 @@ class Setting extends React.Component {
       <section className={`${grid['col-sm-12']} ${grid['col-md-8']}`}>
         <h4 className={`${allowAuthClass}`}>{t('Security')}</h4>
         <div className={styles.item}>
-          <label className={`${allowAuthClass}`}>{t('2nd passphrase (Fee: 5 LSK)')}</label>
+          <label className={`${allowAuthClass}`}>{t('second passphrase (Fee: 5 LSK)')}</label>
```
Comment (slaweet) [inline src/components/setting/setting.js]: `second` -> `Second` to be consistent with the rest of settings items

File: src/components/transactions/transactionType.js [hunk 2]
```diff
@@ -13,7 +13,7 @@ const TransactionType = (props) => {
       type = t('Second Passphrase Registration');
```
Comment (slaweet) [inline src/components/transactions/transactionType.js]: It wasn't on the list, but to be consistent all other transaction types should also have only the first letter capital, e.g.: `Second Passphrase Registration` -> `Second passphrase registration`

**Comment by slaweet** [comment]
Changes like `Ok, I'm Done -> Ok, I'm done` and `Go To Your Dashboard -> Go to your Dashboard` are a matter of the buttons having css ` text-transform: capitalize;`
