### PR TITLE
Hide Fee field on Request transfer - Closes #1052

### LINKED ISSUE #1052: Request transfer: While entering amount "fee" is shown
### Steps to reproduce

1. Got to wallet/dashboard
1. Choose Request tab
1. Request specific transfer

### Actual result
I see the amount of "Fee"
It makes no sence to show requesting specific amount
it makes me think either should i deduct it or add up to the amount
or it makes me think that i should pay it to request 

### Expected result
I don't see any fee

image

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What was the problem?
Fee field was show on requesting amount
### How did I fix it?
Hide fee field for request amount

### Review checklist
- The PR solves #1052
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/request/specifyRequest.js [hunk 1]
```diff
@@ -68,6 +68,7 @@ class SpecifyRequest extends React.Component {
             value={this.state.amount.value}
             onChange={this.handleChange.bind(this, 'amount')}
             t={this.props.t}
+            isRequesting
```
Comment (faival) [inline src/components/request/specifyRequest.js]: can't find the value of `isRequesting` in any line along `specifyRequest.js` can you clarify where is coming from or how is initialised?

Comment (michaeltomasik) [reply src/components/request/specifyRequest.js]: This is short for `isRequesting = true` so it works like switch between Requesting and sending module

Comment (faival) [reply src/components/request/specifyRequest.js]: all clear 🌮
