### PR TITLE
Fix actions unit tests migration - Closes #1006

### LINKED ISSUE #1006: Account, Delegate, Dialog, followedAccounts Actions Unit Tests should be covered - Core 1.0.0 Migration
### Expected behaviour
- child of #996

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What was the problem?
Unit tests not migrated
### Review checklist
- The PR solves #1006 
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/store/middlewares/account.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ const delegateRegistration = (store, action) => {
     transactionTypes.registerDelegate,
   );
   const state = store.getState();
-
+  console.log(delegateRegistrationTx, 'delegateRegistrationTx');
```
Comment (slaweet) [inline src/store/middlewares/account.js]: Forgotten console.log

File: src/utils/api/delegate.test.js [hunk 2]
```diff
@@ -89,46 +105,8 @@ describe('Utils: Delegate', () => {
...
-        username: 'test',
-        secret: 'wagon dens',
-      };
-      peersMock.expects('requestToActivePeer').withArgs(activePeer, 'delegates', data)
-        .returnsPromise().resolves('resolved promise');
-
-      const returnedPromise = registerDelegate(activePeer, data.username, data.secret);
-      return expect(returnedPromise).to.eventually.equal('resolved promise');
-    });
-  });
```
Comment (slaweet) [inline src/utils/api/delegate.test.js]: Why could these tests be removed?
