### PR TITLE
Fix order of menu items, and i18n strings for onboarding - Closes #1174

### LINKED ISSUE #1174: Wrong order of items in main menu and wrong i18n strings in onboarding
### Expected behaviour
- Wallet menu entry should be before Delegates in document order.
- Onboarding item for settings should not longer say `and repeat the onboarding here`, because it was removed from settings.

### PR DESCRIPTION
**Pull request by faival**
### Review checklist
- The PR solves #1174 
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/mainMenu/mainMenu.js [hunk 1]
```diff
@@ -105,7 +105,7 @@ class MainMenu extends React.Component {
     ];
 
     if (showDelegate) {
-      tabs.splice(tabs.length - 2, 0, {
+      tabs.splice(tabs.length - 1, 0, {
```
Comment (slaweet) [inline src/components/mainMenu/mainMenu.js]: It's not the first time we have a problem with the index here, I would rather put delegates item inside `tabs` array and `.filter` it by `id === 'delegates'` instead of `splice`ing based on the index.

Comment (faival) [reply src/components/mainMenu/mainMenu.js]: 👍
