### PR TITLE
Transactions to 'yourself' are all seen as "account initialization" - Closes #1281

### LINKED ISSUE #1281: Transactions to 'yourself' are all seen as "account initialization"
If you send a transaction to yourself using the hub, they are all seen as "account initialization", this look weird/wrong. If an initialization has already performed, the message shouldn't be repeated.

### Steps to reproduce

Use the hub to send lisk to your **own** address.

### Actual result

Address is mentioned as "account initialization"

### Expected result

Address should mention the senders address. 

### Solution

Save locally if an "account initialization" is performed. After the first time the hub should mentioned the senders address, even though its the same as the receiver.

### Screenshot (if appropriate)
image

### PR DESCRIPTION
**Pull request by bmaggi-lisk**
### What issue have I solved?

-- #1281

### How have I implemented/fixed it?

1. Type 0 transactions to yourself (same sender & receiver) show address instead of "Account initialization"
2. When initializing account the reference message for the transaction is set to "Account initialization"

### How has this been tested?

1. Transfer some amount of LSK to yourself
2. Go to wallet outgoing transactions check for the transaction you made to yourself you should see  recipient (self) address instead of "Account initialization"

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/sendReadable/send.js [hunk 1]
```diff
@@ -79,13 +79,15 @@ class SendReadable extends React.Component {
   send(event) {
     event.preventDefault();
     this.setState({ loading: true });
+    const isAccountInit = this.props.accountInit &&
+      (this.props.account.address === this.state.recipient.value);
```
Comment (slaweet) [inline src/components/sendReadable/send.js]: The second line of the condition is not needed, `this.props.accountInit` should be already all you need.
