### PR TITLE
Second passphrase registration: Ugly timestamp error - Closes #1278

### LINKED ISSUE #1278: Second passphrase registration: Ugly timestamp error
### Steps to reproduce

1. Set your system time ahead of the current actual time
1. Got to settings
1. Register second passphrase

### Actual result

Error message is ugly
Clicking OK does nothing

### Expected result

Nice error message on style

### Version

1.2

### Screenshot (if appropriate)
image

### PR DESCRIPTION
**Pull request by bmaggi-lisk**
### What issue have I solved?

-- #1278

### How have I implemented/fixed it?

Add new action to be dispatched on the rejection that will:
- Set state `secondPassphrase.secondPassphraseStep` to `second-passphrase-register-failure`
- Add new step to ConfirmSecond to tell the user about the error

### How has this been tested?

- Set your system time ahead of the current actual time
- Got to settings
- Register second passphrase

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/passphrase/ConfirmSecond/confirmSecond.js [hunk 1]
```diff
@@ -142,6 +176,18 @@ class confirmSecond extends React.Component {
...
+          <form onSubmit={this.redirectToFirstStep.bind(this)}>
+            <PrimaryButton
+              disabled={false}
+              label={t('Try again')}
+              className={'second-passphrase-register-failure'}
+              onClick={this.redirectToFirstStep.bind(this)}
+            />
+          </form>
+        </TransitionWrapper>
+        */ }
```
Comment (slaweet) [inline src/components/passphrase/ConfirmSecond/confirmSecond.js]: Please remove the commented-out code
